[package]
name = "function-like-compose-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0.39", features = ["extra-traits"] }
quote = "1.0.33"
proc-macro2 = "1.0.69"

[lib]
proc-macro = true